# .github/workflows/metrics.yml
name: Build metrics (2-column)

on:
  schedule:
    - cron: "0 */6 * * *"     # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # LEFT COLUMN: header/community/repos + recent activity + languages + isocalendar
      - name: Generate left column
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: realKeehan
          template: classic
          filename: metrics_left.svg
          config_timezone: Etc/UTC
          base: header, community, repositories, metadata

          # Recent public activity feed (SVG)
          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_days: 14
          plugin_activity_filter: issue, pr, release, fork, star

          # Languages (compact, GitHub colors)
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_colors: github

          # Contribution calendar (full year)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      # RIGHT COLUMN: achievements + followup + stars
      - name: Generate right column
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: realKeehan
          template: classic
          filename: metrics_right.svg
          config_timezone: Etc/UTC
          base: ""

          # Achievements (compact)
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C

          # Open issues/PRs follow-up status
          plugin_followup: yes
          plugin_followup_sections: user, repositories

          # Recently starred
          plugin_stars: yes
          plugin_stars_limit: 6
