name: Update README with recent activity

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update activity section
        uses: jamesgeorge007/github-activity-readme@v0.3.0
        with:
          COMMIT_MSG: "chore: update recent GitHub activity"
          GH_USERNAME: realKeehan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
